FROM router-base:latest

RUN apk add --update --no-cache rp-pppoe

# Copy network information
COPY config/interfaces.template /etc/network/

# Add pppoe-server service
COPY services/pppoe-server/pppoe-server /etc/dinit.d/
RUN dinitctl --offline --services-dir /etc/dinit.d/ enable pppoe-server
COPY --chmod=755 services/pppoe-server/ip-up /etc/ppp/ip-up
COPY --chmod=755 services/pppoe-server/ip-down /etc/ppp/ip-down
COPY --chmod=755 services/pppoe-server/start-dhcpv6-service /usr/local/bin/
COPY services/pppoe-server/pppoe-server-options /etc/ppp/
COPY services/pppoe-server/chap-secrets /etc/ppp/

# Add dhcpv6 service
COPY services/dhcpv6/dhcpv6 /etc/dinit.d/
COPY --chmod=775 services/dhcpv6/start-dhcpv6 /usr/local/bin/

