#!/usr/bin/env python3

import sys
from scapy.all import Ether, sendp

def main():
    if len(sys.argv) != 5:
        print("Usage: ip-event.py <protocol> <interface> <local_ip> <remote_ip>")
        return

    protocol = sys.argv[1]
    interface = sys.argv[2]
    local_ip = sys.argv[3]
    remote_ip = sys.argv[4]

    print(f"Protocol: {protocol}, Interface: {interface}, Local IP: {local_ip}, Remote IP: {remote_ip}")
    
    send_event('eventbus', 1, 'This is a test event')

def send_event(interface, event_type, event_data):
    # Construct the Ethernet frame
    frame = Ether(dst="ff:ff:ff:ff:ff:ff", src="00:0c:29:ab:cd:ef", type=0x88b5) / event_type.to_bytes(2, byteorder='big') / event_data.encode('utf-8')

    # Send the frame on the specified interface
    sendp(frame, iface=interface, verbose=False)



if __name__ == "__main__":
    main()