# Build a patched version of dhcpd that allows binding to a PPP interface
# This is jank for multiple reasons:
# - dhcpd is slowly being deprecated in favour of Kea DHCP, but Kea seems
#   to have a breaking bug that makes it listen on the peer IP of the PPP
#   interface, which breaks the functionality altogether.
# - This APKBUILD might change and break at any moment, but due to
#   development on dhcpd being basically halted, this is not likely to
#   happen often
# - Because the abuild system is weird the build must be force to run as
#   root, but also signing is a bit of an issue. For now a temp key is
#   generated an copied over to the receiving container.
FROM alpine:edge AS builder

RUN apk add --no-cache alpine-sdk git
RUN git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git /aports

WORKDIR /aports/main/dhcp

COPY patches/ppp.patch /aports/main/dhcp/ppp.patch 

RUN mkdir /build \
    && ls -la /aports/main/dhcp 
RUN abuild -F deps \
    && abuild -F checksum \
    && sed -i '/^source=".*/a      ppp.patch' APKBUILD \
    && sed -i "/^sha512sums=\".*/a$(sha512sum ppp.patch)" APKBUILD \
    && abuild-keygen -a -n \
    && cp /root/.abuild/*.rsa.pub /etc/apk/keys/
RUN abuild -r -F -P /build \
    && ls -laR /build




FROM alpine:edge

# Add base packages
RUN apk add --update --no-cache nano \
        ifupdown-ng ifupdown-ng-ppp ppp bridge \
        python3 scapy busybox-openrc \
        tcpdump strace file \
        kea kea-dhcp-ddns kea-hook-bootp kea-hook-run-script \
        radvd dnsmasq dhcpcd \
        dinit bash gettext syslog-ng

# Add patched dhcpd
COPY --from=builder /build/main/x86_64/*.apk /tmp/
COPY --from=builder /root/.abuild/*.rsa.pub /etc/apk/keys/
RUN rm /tmp/dhcp-server-ldap* && apk add --no-cache /tmp/*.apk

# Create directory for dinit services
RUN mkdir -p /etc/dinit.d/boot.d
COPY services/boot/boot /etc/dinit.d/

# Add rename-interfaces service
COPY services/rename-interfaces/rename-interfaces /etc/dinit.d/
COPY --chmod=775 services/rename-interfaces/rename-interfaces-env /usr/local/bin
RUN dinitctl --offline --services-dir /etc/dinit.d/ enable rename-interfaces

# Add network service
COPY services/network/network /etc/dinit.d/
COPY --chmod=775 services/network/start-network /usr/local/bin
RUN dinitctl --offline --services-dir /etc/dinit.d/ enable network

# Add syslog-ng service
COPY services/syslog-ng/syslog-ng /etc/dinit.d/
COPY services/syslog-ng/syslog-ng.conf /etc/syslog-ng/
RUN dinitctl --offline --services-dir /etc/dinit.d/ enable syslog-ng

# Add entrypoint
COPY --chmod=775 docker-entrypoint.sh /

WORKDIR /

ENTRYPOINT ["/docker-entrypoint.sh"]

