FROM router-base:latest

RUN apk add --update --no-cache busybox-extras

# Copy network information
COPY config/interfaces /etc/network/interfaces

# Add httpd service
COPY services/httpd/httpd /etc/dinit.d/
RUN dinitctl --offline --services-dir /etc/dinit.d/ enable httpd
COPY services/httpd/index.html /var/www/

