#!/bin/sh

GENERATOR="/etc/network/interfaces.generator"
TEMPLATE="/etc/network/interfaces.template"
OUTPUT="/etc/network/interfaces"

if [ -f "$GENERATOR" ]; then
    eval "$GENERATOR" > "$OUTPUT"
    logger -p syslog.info "Created $OUTPUT using $GENERATOR"
elif [ -f "$TEMPLATE" ]; then
    envsubst < "$TEMPLATE" > "$OUTPUT"
    logger -p syslog.info "Created $OUTPUT using $TEMPLATE"
elif [ -f "$OUTPUT" ]; then
    logger -p syslog.info "Using $OUTPUT for network interfaces"
else
    logger -p syslog.err "Neither $TEMPLATE nor $OUTPUT is present"
    exit 1
fi

ifup -a