#!/usr/bin/env python3

import sys
from scapy.all import Ether, sendp

def main():
    if len(sys.argv) != 4:
        print("Usage: ip-event.py <protocol> <ipv4 IP/ipv6 prefix> <reason>")
        return

    protocol = sys.argv[1]
    ip_or_prefix = sys.argv[2]
    reason = sys.argv[3]

    print(f"Protocol: {protocol}, Local IP or prefix: {ip_or_prefix}, Reason: {reason}")
    
    send_event('eventbus', 1, 'This is a test event')

def send_event(interface, event_type, event_data):
    # Construct the Ethernet frame
    frame = Ether(dst="ff:ff:ff:ff:ff:ff", src="00:0c:29:ab:cd:ef", type=0x88b5) / event_type.to_bytes(2, byteorder='big') / event_data.encode('utf-8')

    # Send the frame on the specified interface
    sendp(frame, iface=interface, verbose=False)



if __name__ == "__main__":
    main()