# Build a patched version of dhcpd that allows binding to a PPP interface
# This is jank for multiple reasons:
# - dhcpd is slowly being deprecated in favour of Kea DHCP, but Kea seems
#   to have a breaking bug that makes it listen on the peer IP of the PPP
#   interface, which breaks the functionality altogether.
# - This APKBUILD might change and break at any moment, but due to
#   development on dhcpd being basically halted, this is not likely to
#   happen often
# - Because the abuild system is weird the build must be force to run as
#   root, but also signing is a bit of an issue. For now a temp key is
#   generated an copied over to the receiving container.
FROM alpine:3.20 AS builder

RUN apk add --no-cache alpine-sdk git
RUN git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git /aports

WORKDIR /aports/main/dhcp

COPY patches/ppp.patch /aports/main/dhcp/ppp.patch 

RUN mkdir /build \
    && ls -la /aports/main/dhcp 
RUN abuild -F deps \
    && abuild -F checksum \
    && sed -i '/^source=".*/a      ppp.patch' APKBUILD \
    && sed -i "/^sha512sums=\".*/a$(sha512sum ppp.patch)" APKBUILD \
    && abuild-keygen -a -n \
    && cp /root/.abuild/*.rsa.pub /etc/apk/keys/
RUN abuild -r -F -P /build \
    && ls -laR /build




FROM alpine:3.20

# Add base packages
RUN apk add --update --no-cache nano \
        ifupdown-ng ifupdown-ng-ppp ppp bridge \
        python3 scapy busybox-openrc \
        tcpdump strace file \
        kea radvd dnsmasq \
        supervisor bash inotify-tools

# Add patched dhcpd
COPY --from=builder /build/main/x86_64/*.apk /tmp/
COPY --from=builder /root/.abuild/*.rsa.pub /etc/apk/keys/
RUN rm /tmp/dhcp-server-ldap* && apk add --no-cache /tmp/*.apk

# Configure supervisord and create folder to store services
COPY supervisord.conf /etc/supervisord.conf
RUN mkdir -p /etc/supervisor.d/




WORKDIR /

CMD ["/usr/bin/supervisord -n -c /etc/supervisord.conf"]

